apiVersion: v1
kind: Service
metadata:
  name: mkdocs-nginx-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-04fd9a306faa51064
spec:
  selector:
    app: mkdocs-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
